// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-0jFtEPe34eiBXriNIEaajYGnIyHVhs',
    appId: '1:836519579068:web:aca93b16e6a1d01f9fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    authDomain: 'ecommerce-5ae51.firebaseapp.com',
    storageBucket: 'ecommerce-5ae51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDha73sa2FmGmbiugrdqCnGrVFd_xuqg',
    appId: '1:836519579068:android:2fe6f5a8832123ea9fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cwnTFwnaZxPuicZho5DiB-FDlGPOtF4',
    appId: '1:836519579068:ios:a0c7f3988c1749c99fafb9',
    messagingSenderId: '836519579068',
    projectId: 'ecommerce-5ae51',
    storageBucket: 'ecommerce-5ae51.firebasestorage.app',
    iosBundleId: 'com.foodi1.app',
  );

}